app/blueprints/billings/models/coupon.py
from app.extensions import db

class Coupon(db.model):
    """
    Coupon Class
    """

app/blueprints/billings/models/creditcard.py
import datetime

from app.extensions import db
from app.lib.utility_datetime import time_delta
from app.lib.utility_sqlalchemy import ResourceMixin


class CreditCard(db.Model, ResourceMixin):
    """

    """
    IS_EXPIRING_THRESHOLD_MONTHS = 2


    __tablename__ = "credit_cards"

    id = db.Column(db.Integer, primary_key=True,index=True)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id",ondelete="CASCADE", onupdate="CASCADE"),
                        index=True, nullable=False)

    brand = db.Column(db.String(128))
    last4 = db.Column(db.Integer)
    expiry_date = db.Column(db.Date,index=True)
    is_expiring = db.Column(db.Boolean(),server_default='0',nullable=False)

    def __init__(self,**kwargs):
        #Call SQL-ALCHEMY Default's Constructor
        super(CreditCard,self).__init__(**kwargs)


    @classmethod
    def extract_credit_card_information(cls,customer):
        """

        Extract the credit card info from a payment customer object.

        :param customer: Payment customer
        :type customer: Payment customer
        :return: dict
        """

        card_info = customer.sources.data[0]
        exp_Date = datetime.date(card_info.exp_year,card_info.exp_month,1)

        card = {'brand': card_info.brand,
                "last4": card_info.last4,
                "exp_date":exp_Date,
                "is_expiring":CreditCard.is_expiring_soon(exp_Date=exp_Date)

        }

        return card

    @classmethod
    def is_expiring_soon(cls,exp_date=None, compare_date=None):


        """

        :param exp_date:
        :param compare_date:
        :return:
        """

        return exp_date<=time_delta(CreditCard.IS_EXPIRING_THRESHOLD_MONTHS,compare_date)

    @classmethod
    def mark_old_credit_cards(cls,compare_date=None):
        """

        :param compare_date:
        :return:
        """

        today_with_Delta = time_delta(CreditCard.IS_EXPIRING_THRESHOLD_MONTHS,compare_date)

        CreditCard.query.filter(CreditCard.expiry_date<=today_with_Delta).update({CreditCard.is_expiring:True})

        return db.session.commit()

app/blueprints/billings/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, StringField
from wtforms.validators import DataRequired, Length, Optional


class CreditCardForm(FlaskForm):
    stripe_key = HiddenField('stripe_publishable_key',[DataRequired(),Length(1,128)])
    plan = HiddenField('Plan',[DataRequired(),Length(1,128)])
    coupon_code = StringField("Coupon Code", [Optional(), Length(1,128)])
    name = StringField("Name on Card", [DataRequired(), Length(1,128)])



class UpdateSubscriptionForm(FlaskForm):
    coupon_code = StringField("Do You have An Active Coupon?", [Optional(), Length(1,254)])


class CancelSubscription(FlaskForm):
    """

    """

app/blueprints/user/forms.py
from flask_wtf import FlaskForm
from wtforms import HiddenField, StringField, PasswordField
from wtforms.validators import DataRequired, Length, Regexp, Optional, Email
from wtforms_alchemy import Unique, ModelForm
from wtforms_components import EmailField

from app.blueprints.user.model import User
from app.blueprints.user.validators import ensure_existing_password_matches, ensure_identity_exists
from app.extensions import db


class LoginForm(FlaskForm):
    next = HiddenField()
    identity = StringField("Username or email", [DataRequired(), Length(1,256)])
    password = PasswordField("Password", validators=[DataRequired(), Length(8,128)])


class BeginPasswordResetForm(FlaskForm):
    identity = StringField('Username or Email', validators=[DataRequired(), Length(1,128), ensure_identity_exists])


class PasswordRestForm(FlaskForm):
    reset_token = HiddenField()
    password = PasswordField('Password',validators=[DataRequired(), Length(8,128)])


class SignupForm(ModelForm,FlaskForm):
    email = EmailField(validators=[DataRequired(), Email(), Unique(User.email, get_session=lambda : db.session)])
    password = PasswordField("Password", validators=[DataRequired(), Length(8,128)])

class WelcomeForm(ModelForm,FlaskForm):
    username_message = 'Letters, numbers and underscores only please'

    username = StringField(validators=[Unique(User.username, get_session = lambda : db.session),DataRequired(),
                                              Length(1,16), Regexp('^\w+$', message=username_message)])


class UpdateCredentials(ModelForm,FlaskForm):

    current_password = PasswordField( 'Current password',
                                      [DataRequired(),
                                       Length( 8, 128 ), ensure_existing_password_matches] )

    email = EmailField(validators=[
        Email(),
        Unique(
            User.email,
            get_session=lambda: db.session
        )
    ] )
    password = PasswordField( 'Password', [Optional(), Length( 8, 128 )] )


class PasswordResetForm(FlaskForm):
    reset_token = HiddenField()
    password = PasswordField('Password', [DataRequired(), Length(8, 128)])

app/blueprints/billings/__init__.py
from flask.blueprints import Blueprint

billing = Blueprint("billing", __name__, template_folder="templates")


from app.blueprints.billings import views

app/blueprints/billings/views.py
from flask import flash, url_for, request, current_app, render_template, app
from flask_login import current_user
from flask_login import login_required
from werkzeug.utils import redirect

from app.blueprints.billings import billing
from app.blueprints.billings.forms import CreditCardForm, UpdateSubscriptionForm, CancelSubscription
from app.blueprints.billings.models.creditcard import CreditCard
from app.blueprints.billings.models.subscriptions import Subscription


@billing.route("/create", methods=['GET','POST'])
@login_required
def create():
    if current_user.subscription:
        flash("The user is already subscribed")
        return redirect(url_for("user.settings"))

    plan = request.args.get("plan")
    subscription_plan = Subscription.stripe_get_plan_by_id(plan)


    if subscription_plan is None and request.method == 'GET':
        flash("No such plan")
        return redirect(url_for("billing.pricing"))

    stripe_key =  current_app.config.get('STRIPE_PUBLIC_API_KEY')
    form = CreditCardForm(stripe_key=stripe_key, plan=plan)

    if form.validate_on_submit():
        subscription = Subscription()
        created=subscription.create(user=current_user,
                            name= request.form.get('name'),
                            plan=request.form.get('plan'),
                            coupon=request.form.get("coupon_code"),
                            token=request.form.get("stripe_token"))
        if created:
            flash("Awesome Thanks for subscribing", 'Thanks')
        else:
            flash("you must have a javascript enabled", 'Error')


        return redirect(url_for("user.settings"))

    return render_template("billing/payment_method.html",form=form,plan=subscription_plan)



@billing.route("/updatecard",methods=['GET','POST'])
@login_required
def update_credit_card():

    if not current_user.creditcard:
        flash("Please make sure you have the card added before")
        return redirect(url_for("user.settings"))

    active_plan = Subscription.stripe_get_plan_by_id(current_user.subscription.plan)

    card = current_user.creditcard
    stripe_key = current_app.config.get('STRIPE_PUBLIC_API_KEY')

    form = CreditCardForm(stripe_key=stripe_key,plan=active_plan,name=current_user.name)

    if form.validate_on_submit():
        subscription = Subscription()
        updated = subscription.update_payment_method(user=current_user,
                                           credit_card = card,
                                           name = request.form.get("name"),
                                           token = request.form.get("token"))

        if updated:
            flash("The details have been updated", "success")

        else:
            flash("your javascript is disabled", "failure")
        return redirect(url_for('user.settings'))

    render_template("billing/payment_method.html",form=form, plan=active_plan, card_last4=str(CreditCard.last4))


@billing.route("/update",methods=['GET','POST'])
@login_required
def update():

    current_plan = current_user.subscription.plan
    active_plan = Subscription.stripe_get_plan_by_id(current_plan)
    new_plan = Subscription.get_new_plan(request.form.keys())


    plan = Subscription.stripe_get_plan_by_id(new_plan)

    is_same_plan = new_plan == active_plan['id']

    if((new_plan is not None and plan is None) or is_same_plan) and request.method == 'POST':
        return(url_for("billing.update"))

    form = UpdateSubscriptionForm(coupon_code=current_user.subscription.coupon)

    if form.validate_on_submit():
        subscription = Subscription()
        updated = subscription.update(user=current_user,coupon= request.form.get("coupon_code"),plan=plan.get("id"))

        if updated:
            flash("The details have been updated", "success")

        else:
            flash("your javascript is disabled", "failure")
        return redirect(url_for('user.settings'))

    render_template("billing/pricing.html",form=form,plan=app.config.STRIPE_PLANS,active_plan=active_plan)



@billing.route('/cancel',methods=['GET','POST'])
@login_required
def cancel():

    if not current_user.subscription:
        flash('You do not have an active subscription','error')
        return redirect(url_for('user.settings'))

    form = CancelSubscription()

    if form.validate_on_submit():
        subscription = Subscription()
        cancelled = subscription.cancel(user=current_user)

        if cancelled:
            flash("Sorry to have see you go", "Cancelled")
            return redirect(url_for('user.settings'))

    return render_template('billing/cancel.html',form=form)




@billing.route('/pricing')
def pricing():
    if current_user.is_authenticated and current_user.subscription:
        return redirect(url_for('billing.update'))

    form = UpdateSubscriptionForm()

    return render_template('billing/pricing.html', form=form,
                           plans=current_app.config.get('STRIPE_PLANS'))

app/blueprints/user/__init__.py
from flask import Blueprint


user = Blueprint("user", __name__,template_folder='templates')

from app.blueprints.user import views

app/blueprints/user/views.py
from flask import (
    redirect,
    request,
    flash,
    url_for,
    render_template)
from flask_login import (
    login_required,
    login_user,
    current_user,
    logout_user)

from app.blueprints.user import user
from app.blueprints.user.forms import (
    LoginForm,
    BeginPasswordResetForm,
    PasswordResetForm,
    SignupForm,
    WelcomeForm,
    UpdateCredentials)
from app.blueprints.user.model import User
from app.lib.safe_next_url import safe_next_url
from app.lib.util_decorators import anonymous_required


@user.route('/login', methods=['GET', 'POST'])
@anonymous_required()
def login():
    form = LoginForm(next=request.args.get('next'))

    if form.validate_on_submit():
        u = User.find_by_identity(request.form.get('identity'))

        if u and u.authenicate_password(password=request.form.get('password')):
            # As you can see remember me is always enabled, this was a design
            # decision I made because more often than not users want this
            # enabled. This allows for a less complicated login form.
            #
            # If however you want them to be able to select whether or not they
            # should remain logged in then perform the following 3 steps:
            # 1) Replace 'True' below with: request.form.get('remember', False)
            # 2) Uncomment the 'remember' field in user/forms.py#LoginForm
            # 3) Add a checkbox to the login form with the id/name 'remember'

            if login_user(u, remember=True) and u.is_active:
                u.update_activity_tracking(request.remote_addr)

                # Handle optionally redirecting to the next URL safely.
                next_url = request.form.get('next')
                if next_url:
                    return redirect(safe_next_url(next_url))

                return redirect(url_for('user.settings'))
            else:
                flash('This account has been disabled.', 'error')
        else:
            flash('Identity or password is incorrect.', 'error')

    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'success')
    return redirect(url_for('user.login'))


@user.route('/account/begin_password_reset', methods=['GET', 'POST'])
@anonymous_required()
def begin_password_reset():
    form = BeginPasswordResetForm()

    if form.validate_on_submit():
        u = User.initialize_password_reset(request.form.get('identity'))

        flash('An email has been sent to {0}.'.format(u.email), 'success')
        return redirect(url_for('user.password_reset'))

    return render_template('user/begin_password_reset.html', form=form)


@user.route('/account/password_reset', methods=['GET', 'POST'])
@anonymous_required()
def password_reset():
    form = PasswordResetForm(reset_token=request.args.get('reset_token'))

    if form.validate_on_submit():
        u = User.decode_password_reset_token(request.form.get('reset_token'))

        if u is None:
            flash('Your reset token has expired or was tampered with.',
                  'error')
            return redirect(url_for('user.begin_password_reset'))

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Your password has been reset.', 'success')
            return redirect(url_for('user.settings'))

    return render_template('user/password_reset.html', form=form)


@user.route('/signup', methods=['GET', 'POST'])
@anonymous_required()
def signup():
    form = SignupForm()

    if form.validate_on_submit():
        u = User()

        form.populate_obj(u)
        u.password = User.encrypt_password(request.form.get('password'))
        u.save()

        if login_user(u):
            flash('Awesome, thanks for signing up!', 'success')
            return redirect(url_for('user.welcome'))

    return render_template('user/signup.html', form=form)


@user.route('/welcome', methods=['GET', 'POST'])
@login_required
def welcome():
    if current_user.username:
        flash('You already picked a username.', 'warning')
        return redirect(url_for('user.settings'))

    form = WelcomeForm()

    if form.validate_on_submit():
        current_user.username = request.form.get('username')
        current_user.save()

        flash('Sign up is complete, enjoy our services.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/welcome.html', form=form)


@user.route('/settings')
@login_required
def settings():
    return render_template('user/settings.html')


@user.route('/settings/update_credentials', methods=['GET', 'POST'])
@login_required
def update_credentials():
    form = UpdateCredentials(current_user, uid=current_user.id)

    if form.validate_on_submit():
        new_password = request.form.get('password', '')
        current_user.email = request.form.get('email')

        if new_password:
            current_user.password = User.encrypt_password(new_password)

        current_user.save()

        flash('Your sign in settings have been updated.', 'success')
        return redirect(url_for('user.settings'))

    return render_template('user/update_credentials.html', form=form)

app/templates/macros/billing.html
{% macro card_expiring_warning() -%}
  {% if current_user.is_authenticated and 
        current_user.subscription and current_user.credit_card.is_expiring %}
    <div class="alert alert-warning" role="alert">
      <div class="container">
        Your credit card is going to expire soon,
        <a href="{{ url_for('billing.update_payment_method') }}">
          please update it</a>
        .
      </div>
    </div>
  {% endif %}
{%- endmacro %}


{% macro plan(plan) -%}
  <div class="col-md-4{{ ' scale-up' if plan.metadata.recommended }} {{ ' quarter-faded' if not plan.metadata.recommended }}">
    <div class="panel panel-default{{ ' panel-danger' if plan.metadata.recommended }}">
      <div class="panel-heading text-center"><h3>{{ plan.name }}</h3></div>
      <div class="panel-body">
        {{ caller () }}

        {% if current_user.is_authenticated %}
          {% if current_user.subscription %}
            {% if plan == active_plan %}
              <strong class="btn btn-default btn-lg btn-block">
                Current plan
              </strong>
            {% else %}
              <button id="submit_{{ plan.id }}" name="submit_{{ plan.id }}"
                      class="btn btn-primary btn-lg btn-block">
                <img src="{{ url_for('static', filename='images/spinner.gif') }}"
                     class="spinner"
                     width="16" height="11" alt="Spinner"/>
                Change plan
              </button>
            {% endif %}
          {% else %}
            <a href="{{ url_for('billing.create', plan=plan.id) }}"
               class="btn btn-primary btn-lg btn-block">Continue</a>
          {% endif %}
        {% else %}
          <a href="{{ url_for('user.signup') }}"
             class="btn btn-primary btn-lg btn-block">
            Sign up
          </a>
        {% endif %}

        <p class="small text-muted sm-margin-top text-center">
          ${{ plan.amount }} / {{ plan.interval }}
        </p>
      </div>
    </div>
  </div>
{%- endmacro %}


{% macro coupon_data(coupon) -%}
  {% if coupon.amount_off %}
    {% set discount = '$' + coupon.amount_off  %}
  {% else %}
    {% set discount = coupon.percent_off | string + '%' %}
  {% endif %}
  {% if coupon.duration == 'forever' %}
    {% set label = 'It is saving you ' + discount + ' per month forever.' %}
  {% elif coupon.duration == 'once' %}
    {% set label = 'It saved you ' + discount + ' this month.' %}
  {% else %}
    {% set label = 'It is saving you ' + discount + ' for the next ' + coupon.duration_in_months | string + ' months.' %}
  {% endif %}

  {{ label }}
{%- endmacro %}


{% macro coupon_duration_tag_for(coupon) -%}
  {% if coupon.duration == 'forever' %}
    <span class="label label-success">Forever</span>
  {% elif coupon.duration == 'once' %}
    <span class="label label-warning">Once</span>
  {% else %}
    <span class="label label-info">
      {{ coupon.duration_in_months }} months
    </span>
  {% endif %}
{%- endmacro %}


{% macro coupon_expiration(coupon) -%}
  {% if coupon.redeem_by %}
    <time class="from-now"
          data-datetime="{{ coupon.redeem_by }}">
      {{ coupon.redeem_by }}
    </time>
  {% elif coupon.duration_in_months %}
    &mdash;
  {% else %}
    Never
  {% endif %}
{%- endmacro %}


{% macro coupon_redeemed(times_redeemed, max_redemptions) -%}
  {% set total = max_redemptions if max_redemptions else '&infin;' | safe %}
  {{ times_redeemed }} / {{ total }}
{%- endmacro %}


{% macro coupon_discount(amount_off, percent_off) -%}
  {% if amount_off %}
    ${{ amount_off  }}
  {% else %}
    {{ percent_off }}%
  {% endif %}
{%- endmacro %}


{% macro subscription_details(coupon) -%}
  <h2>Subscription details</h2>
  {% if coupon %}
    <div class="alert alert-info alert-small">
      Coupon code <strong>{{ coupon.code }}</strong> is applied to your
      subscription.
    </div>
    <span class="small text-muted">
      {{ coupon_data(coupon) }}
    </span>
    <br class="sm-margin-bottom">
    <br class="sm-margin-bottom">
  {% endif %}
{%- endmacro %}


{% macro upcoming_invoice(invoice) -%}
  {% if invoice == None %}
    <h3>No upcoming payments</h3>
    <p>You are not currently subscribed, so there's nothing to see here.</p>
  {% else %}
    <table class="table table-striped sm-margin-bottom">
      <thead>
        <tr>
          <th>Subscription</th>
          <th>Description</th>
          <th>Next billing date</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>{{ invoice.plan }}</td>
          <td>{{ invoice.description }}</td>
          <td>
            <time class="short-date" data-datetime="{{ invoice.next_bill_on }}">
              {{ invoice.next_bill_on }}
            </time>
          </td>
          <td>
            ${{ invoice.amount_due }}
            <span class="color--muted"> / {{ invoice.interval }}</span>
          </td>
        </tr>
      </tbody>
    </table>
  {% endif %}
{%- endmacro %}


{% macro invoices(invoices) -%}
  <h2>Recent billing history</h2>
  {% if invoices.count() == 0 %}
    <h4>No invoices found</h4>
    <p>This isn't an error. You just haven't been invoiced yet.</p>
  {% else %}
    <table class="table table-striped sm-margin-bottom">
      <thead>
        <tr>
          <th>Date</th>
          <th>Method</th>
          <th>Description</th>
          <th>Service period</th>
          <th>Tax</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
      {% for invoice in invoices %}
        <tr>
          <td>
            <time class="from-now" data-datetime="{{ invoice.created_on }}">
              {{ invoice.created_on }}
            </time>
          </td>
          <td class="small">
            {{ invoice.brand }} ****{{ invoice.last4 }}
          </td>
          <td class="small">{{ invoice.description }}</td>
          <td>
            <time class="short-date" data-datetime="{{ invoice.period_start_on }}">
              {{ invoice.period_start_on }}
            </time>
            <span class="text-info">&mdash;</span>
            <time class="short-date" data-datetime="{{ invoice.period_end_on }}">
              {{ invoice.period_end_on }}
            </time>
          </td>
          <td title="{{ (invoice.tax_percent | round(2)) | string + '%' if invoice.tax_percent }}">
            {{ '$' + invoice.tax  if invoice.tax }}
          </td>
          <td title="{{ invoice.currency }}">
            ${{ invoice.total  }}
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  {% endif %}
{%- endmacro %}

app/templates/macros/flash.html
{# Render Flask messages. #}
{%- macro render() -%}
  {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
      <div id="flash-messages" class="row sm-margin-top">
        {% for category, msg in messages %}
          <div class="alert alert-{{ category }}" role="alert">
            {{ msg }}
          </div>
        {% endfor %}
      </div>
    {% endif %}
  {% endwith %}
{%- endmacro -%}

app/templates/macros/form.html
{# Render a form field's label with visual aid to see if it's required. #}
{%- macro field_label(f) -%}
  <label for="{{ f.id }}">
    {%- if f.flags.required -%}
      <strong>{{ f.label.text }}</strong>
    {%- else %}
      {{ f.label.text }}
    {%- endif %}
  </label>
{%- endmacro -%}


{# Render a form field's errors. #}
{%- macro field_errors(f) -%}
  {% if f.errors %}
    <ul class="list-unstyled text-danger field-error">
      {% for error in f.errors %}
        <li>{{ error | e }}</li>
      {% endfor %}
    </ul>
  {% endif %}
{%- endmacro -%}


{# Render a form field. #}
{%- macro field(f, css_class='form-control') -%}
  {{ f(class=css_class, **kwargs) }}
{%- endmacro -%}


{# Render a checkbox field. #}
{%- macro checkbox_field(f) -%}
  {{ f(type='checkbox', **kwargs) }} {{ f.label }}
{%- endmacro -%}


{# Render a form group with errors for various field types. #}
{%- macro form_group(f, css_class='') -%}
  {% if f.errors %}
    {% set css_class = css_class + ' has-error ' + kwargs.pop('class', '') %}
  {% endif %}

  {% if f.type == 'BooleanField' %}
    <div class="checkbox {{ css_class }}">
    {{ checkbox_field(f, **kwargs) }}
  {% else %}
    <div class="form-group {{ css_class }}">
    {{ field_label(f) }}
    {{ field(f, **kwargs) }}
  {% endif %}

    {{ field_errors(f) }}
    {{ caller () }}
  </div>
{%- endmacro %}


{# Render a form tag that contains a CSRF token and all hidden fields. #}
{%- macro form_tag(endpoint, fid='', css_class='', method='post') -%}
  <form action="{{ url_for(endpoint, **kwargs) }}" method="{{ method }}"
        id="{{ fid }}" class="{{ css_class }}" role="form">
    {{ form.hidden_tag() }}
    {{ caller () }}
  </form>
{%- endmacro -%}


{# Render a form for searching. #}
{%- macro search(endpoint) -%}
  {% call form_tag(endpoint, method='get') %}
    <label for="q"></label>
    <div class="input-group md-margin-bottom">
      <input type="text" class="form-control"
             id="q" name="q" value="{{ request.args.get('q', '') }}"
             placeholder="Search by typing, then press enter...">
    <span class="input-group-addon">
      <i class="fa fa-fw fa-search"></i>
    </span>
    </div>
  {% endcall %}
{%- endmacro -%}

app/templates/macros/items.html
{# Toggle sorting order on a specific field. #}
{% macro sort(field, title_header=None) -%}
  {% set sort = request.args.get('sort', None) %}
  {% set direction = request.args.get('direction', 'asc') %}
  {% set q = request.args.get('q', '') %}

  {% if title_header == None %}
    {% set label = field | title %}
  {% else %}
    {% set label = title_header %}
  {% endif %}

  {% if sort == field and direction == 'asc' %}
    {% set direction = 'desc' %}
  {% else %}
    {% set direction = 'asc' %}
  {% endif %}

  {% if sort == field %}
    {% set css = direction %}
  {% else %}
    {% set css = 'sort' %}
  {% endif %}

  <a class="{{ css }}" href="{{ url_for(request.endpoint,
                                        q=q,
                                        sort=field,
                                        direction=direction,
                                        **request.view_args) }}">{{ label }}</a>
{%- endmacro %}


{# Paginate through a resource. #}
{% macro paginate(resource) -%}
  {% set args = request.args.to_dict() %}

  <ul class="pagination">
    <li class="{{ 'disabled' if resource.page == 1 }}">
      <a href="{{ url_for(request.endpoint, page=1, **args) }}"
          aria-label="First">
        &laquo; First
      </a>
    </li>
    <li class="{{ 'disabled' if not resource.has_prev }}">
      <a href="{{ url_for(request.endpoint, page=resource.page - 1, **args) }}"
          aria-label="Previous">
        Prev
      </a>
    </li>
  {%- for page in resource.iter_pages() %}
    <li class="{{ 'active' if page and page == resource.page }}">
      {% if page %}
        {% if page != resource.page %}
          <a href="{{ url_for(request.endpoint, page=page, **args) }}">{{ page }}</a>
        {% else %}
          <span class="text-muted">{{ page }}</span>
        {% endif %}
      {% else %}
        <span class="ellipsis">…</span>
      {% endif %}
    </li>
  {%- endfor %}
    <li class="{{ 'disabled' if not resource.has_next }}">
      <a href="{{ url_for(request.endpoint, page=resource.page + 1, **args) }}"
          aria-label="Next">
        Next
      </a>
    </li>
    <li class="{{ 'disabled' if resource.page == resource.pages }}">
      <a href="{{ url_for(request.endpoint, page=resource.pages, **args) }}"
          aria-label="Last">
        Last &raquo;
      </a>
    </li>
  </ul>
{%- endmacro %}

app/templates/macros/user.html
{% macro role_icon_for(user) -%}
  {% if user.role == 'admin' %}
    <i class="fa fa-3x fa-fw fa-shield" title="Admin"></i>
  {% else %}
    {% if user.subscription %}
      <i class="fa fa-3x fa-fw fa-star text-success" title="Paid member"></i>
    {% else %}
      <i class="fa fa-3x fa-fw fa-user text-muted" title="Member"></i>
    {% endif %}
  {% endif %}
{% endmacro %}